url: https://blackstoneengineering.github.io
baseurl: /glossary-webapp/

# Site settings
title: Glossary
email: email_goes_here
description: "Glossary for all your corporate needs"

# Build settings
markdown: kramdown
permalink: pretty